services:
  postgresql:
    container_name: mysweldo-db
    image: "postgres:16.13-alpine3.22"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${LOCAL_DB}
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - mysweldo-postgres-data:/var/lib/postgresql/data

volumes:
  mysweldo-postgres-data:
