services:
  spring:
    container_name: mysweldo-server
    image: ghcr.io/iodsky/mysweldo-api:latest
    restart: always
    ports:
      - 8001:8001
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mysweldo-api.rule=Host(`mysweldo-api.iodsky.com`)"
      - "traefik.http.routers.mysweldo-api.entrypoints=websecure"
      - "traefik.http.routers.mysweldo-api.tls=true"
      - "traefik.http.routers.mysweldo-api.tls.certresolver=le"
      - "traefik.http.services.mysweldo-api.loadbalancer.server.port=8001"
    networks:
      - mysweldo-network
      - traefik
networks:
  mysweldo-network:
  traefik:
    external: true